# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-02 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinilo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('artista', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('apartado', models.BooleanField(default=False)),
                ('vendido', models.BooleanField(default=False)),
                ('info', models.TextField()),
            ],
        ),
    ]
